### ISSUE TITLE
Some confusions about event representation form

### ISSUE THREAD

**Issue by yanxiang-wang** [uzh-rpg/deep_ev_tracker#3]
Hello, thanks for releasing the source code. Congrats on getting accepted by CVPR. And I have some confusion about the data processing. 
1. Why do `value = 2*events['p']-1` for polarity?
2. Why do the voxel calculation for range [x0,x0+1]?
```python
for xlim in [x0,x0+1]:
  for ylim in [y0,y0+1]:
      for tlim in [t0,t0+1]:

          mask = (xlim < W) & (xlim >= 0) & (ylim < H) & (ylim >= 0) & (tlim >= 0) & (tlim < self.nb_channels)
          interp_weights = value * (1 - (xlim-events['x']).abs()) * (1 - (ylim-events['y']).abs()) * (1 - (tlim - t_norm).abs())
```
if xlim or ylim is `+1` value, the weights will be zero directly since `(1 - (xlim-events['x']).abs()) * (1 - (ylim-events['y']).abs())` is 0. If so, the situation that xlim is `x0+1` or ylim is `y0+1` is useless. Do I understand it right? Thanks

**Comment by MessikommerNico** [comment]
Once again, apologies for the late response.

Regarding your questions:

1. This is done to convert the polarity from [0, 1] to [-1, 1]
2. The range [x0, x0+1], [y0, y0+1] is done to deal with floating point pixel positions x, y caused by the rectification of the real-world data. By using this range, we spatially distribute the events to the neighboring integer positions. Specifically, for the case of the x-axis, x0 and x0+1 represent integer values, whereas events['x'] is a floating point values. By taking the difference, we get the weights associated with each neighboring pixel.
