### ISSUE TITLE
Being confused about Affine transformations

### ISSUE THREAD

**Issue by DelinQu** [uzh-rpg/deep_ev_tracker#5]
Hi, 

Thanks for your awesome repo of the deep event tracker! I just read your paper and found that to teach the network geometrically robust representations, affine transformations W are applied to the current event patch Pj to obtain an augmented Patch Pj at each prediction step, as formulated in Eq. (6). However, the Affine transformations have 6Dof without the constraints of "s" and "r" according to the MVG book:
![image](https://user-images.githubusercontent.com/60593268/236189637-44c8ba6f-ccb5-4cf7-bbaa-d0836a4a5f12.png)
Hence, affine transformations should be similarity transformations?

**Comment by MessikommerNico** [comment]
Hi,
Many thanks for your interest in our work!
Good point. Yes, we actually construct similarity transformations instead of affine transformations, see also the [dataset.py](https://github.com/uzh-rpg/deep_ev_tracker/blob/master/utils/dataset.py) file. However, we do have affine transformation implemented, see augment_perspective in the [augmentations.py](https://github.com/uzh-rpg/deep_ev_tracker/blob/master/utils/augmentations.py) file. However, this augmentation was not used to obtain the results reported in the paper.
